### PR TITLE
[IMP]Fix Existing Deleted Record issues in Hotel and Update domain in Create Invoice Button in V10

### PR DESCRIPTION
**Pull request by KrishnaPrajapati-SerpentCS**

### CODE REVIEW

**Comment by JayVora-SerpentCS** [comment]
Please fix travis.

**Comment by KrishnaPrajapati-SerpentCS** [comment]
Can I add author name is 'Odoo Community Association (OCA)'  ? Because Travis Error in author name for to add 'OCA'.

**Comment by JayVora-SerpentCS** [comment]
Dont add it.

**Comment by JayVora-SerpentCS** [comment]
Fixes #126

**Pull request merged**
